# Generated by Django 3.2.6 on 2021-09-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
