# Generated by Django 3.2.6 on 2021-09-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_customers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date',
            field=models.DateField(),
        ),
    ]
