# Generated by Django 3.2.6 on 2021-09-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_customers_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans_hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('reciever', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
