# Generated by Django 3.2.6 on 2021-09-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_trans_hist_customer_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans_hist',
            name='customer_detail',
        ),
        migrations.AddField(
            model_name='trans_hist',
            name='customer_detail',
            field=models.ManyToManyField(blank=True, to='pages.Customers'),
        ),
    ]
