# Generated by Django 3.2.6 on 2021-09-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_customers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans_hist',
            name='customer_detail',
        ),
    ]
