# Generated by Django 3.2.6 on 2021-09-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_trans_hist_customer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans_hist',
            name='reciever_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trans_hist',
            name='sender_id',
            field=models.IntegerField(default=0),
        ),
    ]
