# Generated by Django 3.2.6 on 2021-09-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210909_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans_hist',
            name='reciever_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trans_hist',
            name='sender_id',
            field=models.IntegerField(null=True),
        ),
    ]
