# Generated by Django 3.2.6 on 2021-09-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210909_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans_hist',
            name='reciever_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trans_hist',
            name='sender_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
